### ISSUE TITLE
jello开发的模板页面 连续刷新页面 出现http status 500的情况

### ISSUE THREAD

**Issue by wanglinfang2014** [fex-team/jello#15]
请问是否是jello在处理并发访问时存在问题？

HTTP Status 500 - Request processing failed; nested exception is java.util.ConcurrentModificationException

type Exception report

message Request processing failed; nested exception is java.util.ConcurrentModificationException

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.ConcurrentModificationException
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

java.util.ConcurrentModificationException
    java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
    java.util.ArrayList$Itr.next(ArrayList.java:831)
    org.apache.velocity.app.event.EventHandlerUtil.iterateOverEventHandlers(EventHandlerUtil.java:440)
    org.apache.velocity.app.event.EventHandlerUtil.callEventHandlers(EventHandlerUtil.java:416)
    org.apache.velocity.app.event.EventHandlerUtil.includeEvent(EventHandlerUtil.java:246)
    org.apache.velocity.runtime.directive.Parse.render(Parse.java:156)
    com.baidu.fis.velocity.directive.AbstractInclude.render(AbstractInclude.java:52)
    com.baidu.fis.velocity.directive.Extends.doRender(Extends.java:124)
    com.baidu.fis.velocity.directive.Extends.render(Extends.java:51)
    org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
    org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
    org.apache.velocity.Template.merge(Template.java:356)
    org.apache.velocity.Template.merge(Template.java:260)
    org.springframework.web.servlet.view.velocity.VelocityView.mergeTemplate(VelocityView.java:517)
    org.springframework.web.servlet.view.velocity.VelocityView.doRender(VelocityView.java:462)
    org.springframework.web.servlet.view.velocity.VelocityView.renderMergedTemplateModel(VelocityView.java:291)
    org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
    org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:262)
    org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1157)
    org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:927)
    org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:827)
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
    org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.57 logs.

**Comment by hale1106** [comment]
我也遇到了，还是在最重要的客户项目上发生了两次，信任一下全没了：（，所以用最新版的fis-velocity-tools就可彻底解决这个问题吗？！

**Comment by xiangshouding** [comment]
@hale1106 源码就在这儿，其实呢我们这个东西在我们的产品线环境中未出现过大问题，如果在你们的生产环境中有啥问题可能是 case 覆盖的不全，就如同我说的源码就在这儿，可以看源码修改和完善TA，感谢你对 jello 的支持。

**Comment by 2betop** [comment]
@hale1106  先别用最新的，用这个版本。

https://github.com/fex-team/fis-velocity-tools/tree/5c4616c1ca84ca6edacd98328cc42e2d7ac62d4f

**Comment by hale1106** [comment]
@xiangshouding @2betop  请问现在的发布最新版本是几点几的，我们用的是1.3的有这个问题，是否有发布最新的稳定的版本

**Comment by 2betop** [comment]
1.3 的有问题，我来 release 一个最新的稳定版本，你稍等会

**Comment by 2betop** [comment]
v1.8 https://github.com/fex-team/fis-velocity-tools/releases

**Comment by hale1106** [comment]
@2betop 谢谢，那我们用1.8的试试，另外还有两个问题咨询一下，可以加一个我的hi吗，hale1106，我把错误码粘给你
