### ISSUE TITLE
tomac 404

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#26]
jello server start后404找不到页面

release过了

可是不行

**Comment by 2betop** [comment]
什么文件？`jello server open` 命令行打开目录后，去 www 里面看是否有次文件？

**Comment by az8321550** [comment]
> 什么文件？jello server open 命令行打开目录后，去 www 里面看是否有次文件？

有文件目录

**Comment by 2betop** [comment]
就你目前提供的信息，我无法定位问题。请更详细点！

**Comment by az8321550** [comment]
> 就你目前提供的信息，我无法定位问题。请更详细点！

请问还需要提供些什么信息

**Comment by az8321550** [comment]
我昨天还可以跑起来的 没有修改什么东西

**Comment by az8321550** [comment]
没有任何报错

**Comment by az8321550** [comment]
是不是起始路径配置得不对
我自己输入http://127.0.0.1:8080/static/xxx
就可以访问到某些资源

**Comment by 2betop** [comment]
你是请求啥 404 了？我没搞懂。

**Comment by az8321550** [comment]
![ps54z l n6 e 0ii l67_d](https://cloud.githubusercontent.com/assets/5443058/7627953/bf18c5b4-fa4f-11e4-8f2a-6d314f7852ca.png)
就是这个

**Comment by az8321550** [comment]
![gw 3s rf4qr 475ror _x](https://cloud.githubusercontent.com/assets/5443058/7627961/db179f9c-fa4f-11e4-90e5-3fa196e79a12.png)
www目录如上

**Comment by 2betop** [comment]
你试试用用这里面说的规则，预览下你想看的页面。

http://oak.baidu.com/jello-demo/doc/rewrite

**Comment by az8321550** [comment]
.................
突然又好了
奇怪的问题

**Comment by az8321550** [comment]
另外想问一下，我不想用Velocity
只想用jsp
应该怎么配置
目录是什么样的

**Comment by az8321550** [comment]
算了 没有关注 
我自己回去研究吧

**Comment by 2betop** [comment]
1. 引入 fis-velocity-tools.jar
2. 引入 fastjson.jar
3. copy fis.tld
4. 配置 jsp tag

    ```xml
    <jsp-config>
        <taglib>
            <taglib-uri>/fis</taglib-uri>
            <taglib-location>/WEB-INF/fis.tld</taglib-location>
        </taglib>
    </jsp-config>
    ```
5. 应该就好了

**Comment by az8321550** [comment]
....
哥们，有点看不懂啊
能否详细一点 或者 给看看教程啊
