### ISSUE TITLE
加CDN前缀后能否去掉static

### ISSUE THREAD

**Issue by richard-chen-1985** [fex-team/jello#27]
默认的静态资源目录是static，所以我如果加了domain过后，引用路径就会变成cdn.a.com/static/xxx，也就是我的cdn目录也需要这个static目录，感觉加深一层目录深度不舒服，不知道有没有方法可以避免？

**Comment by 2betop** [comment]
通过配置 roadmap.path 可以把 static 去掉。http://fis.baidu.com/docs/api/fis-conf.html#roadmap

**Comment by richard-chen-1985** [comment]
算是搞明白了，谢谢
