### ISSUE TITLE
关于jello输出的html代码

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#29]
css和js总是粘在一起，html标签也不是很好看
![4gb0wk15_ni ey o4 4 ow0](https://cloud.githubusercontent.com/assets/5443058/7650897/8b168556-fb2d-11e4-82ff-6b5497ef6bea.png)

不知道有没有什么方法让html代码格式代，或者压缩一下

**Comment by az8321550** [comment]
有人知道吗？

**Comment by 2betop** [comment]
为什么要关注产出代码的可读性，浏览器能看得懂就行了，只需关心源码的可读性。

**Comment by az8321550** [comment]
那压缩一下节省带宽总是合理的吧

**Comment by 2betop** [comment]
是合理的，但是，现在服务端，基本都设置了 gzip 传输，收益比较小。而且要实现 velociy 模板的压缩，技术成本大 同时 编译时间涉及到词法分析也会非常的长。不值得，所以不打算支持。

**Comment by az8321550** [comment]
恩 有时间我去研究下 提个pull request
