### ISSUE TITLE
jello是否支持fis-postpackager-simple

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#30]
jello是否支持fis-postpackager-simple，
我加了一个自动合并零散资源，但是没有用，
不知道是否支持？

**Comment by xiangshouding** [comment]
jello 支持的方式更牛逼一些，成套的静态资源管理的方法都有了。不需要用静态插件去做合并…

**Comment by az8321550** [comment]
> jello 支持的方式更牛逼一些，成套的静态资源管理的方法都有了。不需要用静态插件去做合并…

能否说下是什么方式？

**Comment by wuanrin** [comment]
同问

**Comment by xiangshouding** [comment]
跑一个 demo 就知道了

```bash
jello release -p #打包
```

**Comment by az8321550** [comment]
> 跑一个 demo 就知道了

这并不是一个好的解决办法!
:-1: :-1: :-1:

**Comment by xiangshouding** [comment]
好歹你要看看表象吧？那你觉着什么样子的表述是更好的？

**Comment by az8321550** [comment]
> 好歹你要看看表象吧？那你觉着什么样子的表述是更好的？

看什么表象？
这样-p 打包并不能达到想要的效果
早就试过了
所以才来寻求更好的解决办法
:hand: :hand: :hand:

**Comment by 2betop** [comment]
simple 只适用于纯前端项目，jello 的打包遵循的是这种理念。

https://github.com/fex-team/fis/issues/488#issuecomment-101989042

没法智能分析出最优解，所以需要自己手动配置。

**Comment by xiangshouding** [comment]
@az8321550 

是这样的，jello是为vm，jsp等后端模板的情况下提供的支持，其实后端模板有一个问题，就是无法完全去静态分析 script、 link 来做资源合并，因为有可能 src，href 的值是个变量。

其实想想都是为了引入资源到页面上，索性就想另外一种办法来做引入，比如

```vm
#require('./a.js');
```

未完待续

**Comment by wuanrin** [comment]
还是没有回答问题啊。
直接设置 pack 打包这个肯定知道啦。
我想了解的是 fis-pure 方案里面的自动打包零散资源的功能，也就是fis-postpackager-simple插件，
在pure里面是好使的，jello里面无效，这个才是问题。

**Comment by xiangshouding** [comment]
jello 不支持相关做法，如果想用，自己撸

**Comment by wuanrin** [comment]
好吧。谢谢解答。

**Comment by 2betop** [comment]
你说的零碎资源是哪些？是说 js 和 css 片段吗？

如果是，那么 jello 里面对应的语法就是 #script()#end 和 #style() #end 请查看 http://oak.baidu.com/jello-demo/velocity/index

http://oak.baidu.com/jello-demo/jsp/index
