### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#32]
我看到你们用这种写法
require("example:widget/widgetA/widgetA.js");
require("common:widgetA/widgetA.js");

请问:
common:
example:
这种写法有什么用，有什么好处，怎么使用
谢谢了！

**Comment by xiangshouding** [comment]
namespace

**Comment by az8321550** [comment]
> namespace

能否详细一点，本人有点不懂

**Comment by az8321550** [comment]
啊，哥们

**Comment by xiangshouding** [comment]
其实起初是这样的，这个来源于具体的项目；

相当年度长某些团队前端极度膨胀，需要很多人来维护，当很多人来维护一个站点的时候不得不把一个站点拆分成多个模块，比如 home、user、admin，每个模块都用一个 svn 去做管理，上线单独上；

那么为了标识每个模块，就用了 namespace 概念，就是你看到的这个东西；

**Comment by az8321550** [comment]
那我请问下，
如果我也想用这种方式，
应该如何去使用呢？
