### ISSUE TITLE
发现一个pack问题

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#33]
fis.config.set('pack',{});

在配置打包的时候，
比如我把3个css打包成一个，这是没问题的，
但是，我请求另一个页面，只用到这3个css中的其中一个，
于是它还是使用这个打包后的css

这个如何解决

**Comment by az8321550** [comment]
这代码有毒

**Comment by xiangshouding** [comment]
https://github.com/fex-team/fis/issues/488#issuecomment-101989042
