### ISSUE TITLE
【已解决】#parent() 指令失效

### ISSUE THREAD

**Issue by ystarlongzi** [fex-team/jello#36]
a.vm 文件：
```
#blocks('div')
<div>div a</div>
#end
```

b.vm  文件：
```
#extends('a.vm')
#blocks('div')
#parent();
<div>div b</div>
#end
#end
```

页面输出：
```
#parent()
div b
```

而不是
```
div a
div b
```

就是 `#paraent()` 指令失效，并没有继承下来。

**Comment by 2betop** [comment]
你看看你的 userDirective 配置了没有

**Comment by ystarlongzi** [comment]
@2betop 在 “/WEB-INF/config/xxx-map.json” 这里配置？这个文件每次 jello release 后，不是会被重写的嘛？

**Comment by 2betop** [comment]
你说的是 jello 环境下面无效，还是后端环境下面无效？

后端在启用 velocity  的时候，有几个 userDirective 的配置项。我说的是那块！

**Comment by ystarlongzi** [comment]
@2betop 嗯嗯，我说的是 jello release 后，预览无效

**Comment by 2betop** [comment]
你先尝试 jello server update 一下试试。

**Comment by 2betop** [comment]
如果在不行的话，请去 jello server info 目录里面去看看，看看 WEB-INF/velocity.properties 文件里面的配置。

**Comment by ystarlongzi** [comment]
@2betop 恩，`jello server update` 后，查看 `WEB-INF/velocity.properties` 文件下的 `userdirective` 值应该缺少 `com.baidu.fis.velocity.directive.Parent` ，然后加上去就可以了。
