### ISSUE TITLE
mod.js跨模块引用报错

### ISSUE THREAD

**Issue by edwardYan** [fex-team/jello#37]
报错信息如下：（诡异的是，注释掉页面引用的一个widge就没有问题，难道有什么冲突，）

Uncaught TypeError: object is not a function   content.js:56 
init   content.js:62
 (anonymous function)      mod.js:128 
next        mod.js:158      
 (anonymous function)       mod.js:74
 callDep         mod.js:156 
(anonymous function)         mod.js:158 
(anonymous function)

求解

**Comment by edwardYan** [comment]
引用方法：Scroll = require('common:widget/js/ui/rolling/rolling.js')

**Comment by xiangshouding** [comment]
更新最新的 mod.js ，github/fex-team/mod

**Comment by edwardYan** [comment]
多谢守鼎
