### ISSUE TITLE
jello release parse sass 报错

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#38]
jello release parse sass 报错
![ysete2_ac wht0oo1 i6 j8](https://cloud.githubusercontent.com/assets/5443058/8073895/be350e82-0f5d-11e5-8fe8-953a7774337e.png)

**Comment by 2betop** [comment]
把 test.sass 列出来

**Comment by az8321550** [comment]
![l nbi9 atubm ej6qknahg](https://cloud.githubusercontent.com/assets/5443058/8073910/04320a02-0f5e-11e5-904f-9b000e048282.png)

**Comment by 2betop** [comment]
稍等，貌似 sass 语法的支持丢失了，我修复下！

**Comment by 2betop** [comment]
@az8321550 升级 fis-parser-sass@0.3.7

已经修复了！
