### ISSUE TITLE
如果我不想我的js文件被define包装，需要怎么配置

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#40]
如果我不想我的js文件被define包装，需要怎么配置

**Comment by 2betop** [comment]
通过 [radmap.path](http://fis.baidu.com/docs/api/fis-conf.html#roadmap) 配置 isMod 为 false

注意规则的顺序问题，和现有属性丢失的问题。

**Comment by fouber** [comment]
@az8321550 

把那个文件从组件化/模块化目录中移出，放到别的目录下不行么

**Comment by az8321550** [comment]
3q 感谢回答！
