### ISSUE TITLE
jello-demo 中 menus的active 模拟数据 是如何生成的

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#43]
jello-demo 中 menus的active 模拟数据
![50 y7eray 8u 4yjcbtjw](https://cloud.githubusercontent.com/assets/5443058/8102030/765da374-104f-11e5-8c22-fd0d090e6e25.png)
 是如何生成的，
在哪里控制的？
找了半天没有找到！

**Comment by 2betop** [comment]
http://oak.baidu.com/jello-demo/jsp/binding

/test/page.jsp

**Comment by 2betop** [comment]
http://oak.baidu.com/jello-demo/jsp/binding

/test/page.jsp

**Comment by az8321550** [comment]
@2betop 我知道这个数据是这样绑上来的，
但是我想问的是这个active是哪来的，
代码中我并没有看到写这个active

**Comment by 2betop** [comment]
你确定你打开看了 /test/page.jsp 文件？

**Comment by 2betop** [comment]
静态东西靠 json 就够了，动态的内容得靠 jsp 文件。

**Comment by az8321550** [comment]
哦，原来是这样！！！
