### ISSUE TITLE
jello release -wl 经常用着用着就挂掉

### ISSUE THREAD

**Issue by az8321550** [fex-team/jello#44]
![v9n7z 8 com nmw8 144 6o](https://cloud.githubusercontent.com/assets/5443058/8123858/77ad3a6e-1103-11e5-848d-60750e94f319.png)

**Comment by az8321550** [comment]
而且改一个页面，通常要等很久，才能消除掉缓存

**Comment by 2betop** [comment]
@xiangshouding 快来围观下

**Comment by xiangshouding** [comment]
已围观，你俩继续。

升级最新的 fis 了吗，如果升级了我看看，感觉是编辑器搞出来了不该在 fis 里面去跑的一些文件出来；

**Comment by 2betop** [comment]
扛不住了，我去把 fis 固定版本！

**Comment by xiangshouding** [comment]
@2betop 

NO，最新版本已经很健壮了，如果最新版本还不稳定那就得重新看看了，我是这个意思；

你固定版本是号的；

**Comment by 2betop** [comment]
@az8321550  已更新 fis ，麻烦升级下试试！

**Comment by az8321550** [comment]
@2betop 如何升级？

**Comment by 2betop** [comment]
```
npm install -g jello
```

**Comment by fouber** [comment]
固定版本号...这是曾经fis早就有过的惨痛教训，现在怎么又经历了一次

**Comment by xiangshouding** [comment]
何止是惨痛，是惨烈；
