### ISSUE TITLE
【已解决】如何向 <body> 标签添加属性

### ISSUE THREAD

**Issue by ystarlongzi** [fex-team/jello#50]
jello 中使用`#body()`来标记`<body>`标签，那么如果想往`<body>`加个属性，比如一个 class 名称，要怎么操作？

**Comment by xiangshouding** [comment]
![image](https://cloud.githubusercontent.com/assets/631195/8391056/7e42db6c-1ce4-11e5-9702-c6be67dc12e5.png)

```
#body('class', 'xxxx')
```

**Comment by ystarlongzi** [comment]
@xiangshouding 谢谢了！文档没看仔细。

**Comment by ystarlongzi** [comment]
@xiangshouding 
现在如果要添加加多个属性的话，仍按照这样的格式，感觉不太容易识别。如下：
```
#body('atr1', 'val1', 'attr2', 'val2', 'attr3', 'val3')
#end
```

然后，尝试使用了下如下的格式，发现`jello`貌似不支持
```
#body('attr1="val1", attr2="val2", attr3="val3"')
#end
```

**Comment by 2betop** [comment]
在 java 里面单引号不是字符串。你试试用双引号括起来！

**Comment by ystarlongzi** [comment]
@2betop 应该不是单双引号的问题，尝试用了下空格作分隔符是可以的。
```
#body('attr1="val1" attr2="val2" attr3="val3"')
#end
```
