### ISSUE TITLE
jello release -wL的L没有生效

### ISSUE THREAD

**Issue by ng-life** [fex-team/jello#54]
修改了jello-demo/page/index.vm中的内容，页面没有自动刷新，手动刷新OK
同样的环境下，单纯的fis是OK的

发现页面没有加载livereload.js

**Comment by ystarlongzi** [comment]
看这里 [自动刷新功能失效的排查步骤](https://github.com/fex-team/fis/issues/109)

**Comment by 2betop** [comment]
不出意外，应该是 #body 里面少了 `<!--livereload-->` 注释

**Comment by gitNodeJs** [comment]
jello release -w 
控制台报错

# Fatal error in ../deps/v8/src/api.cc, line 1062
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
