### ISSUE TITLE
jello 里如何 require 非 js 模块文件

### ISSUE THREAD

**Issue by ystarlongzi** [fex-team/jello#60]
比如有文件目录如下：
```
-- widget
	-- index.js
	-- index.vm
	-- list.tpl
```

其中，`list.tpl`为 html 模板文件，如何在 `index.js` 里获取到 `list.tpl` 模板文件的内容呢？

**Comment by 2betop** [comment]
直接在 js 里面用 `__inline('xxx.tpl')`

**Comment by 2betop** [comment]
建议用 utc，直接能解析成可执行的  fn, 参考 jello-demo 中的配置方式。

**Comment by ystarlongzi** [comment]
嗯嗯，谢谢。。也突然又想起来 fis 的资源嵌入能力！

**Comment by ystarlongzi** [comment]
赞！
