### ISSUE TITLE
#require指令如何解决静态资源绝对引用的问题？

### ISSUE THREAD

**Issue by flyingzl** [fex-team/jello#67]
J2EE应用部署后，有一个context,一般我们可以通过$request.getContextPath来获取绝对路径，然后拼接上静态资源例如，例如 `<script src="$request.contextPath/static/js/require.js"></script>`

由于`#requrie`是根据`map.json`表来映射的，而且我也不可以在`fis-conf.js`中把`url`写死，有什么更好的解决方法？

**Comment by 2betop** [comment]
转移到 https://github.com/fex-team/fis-velocity-tools/issues/11

这个就关了
