### ISSUE TITLE
百度的jar包在哪下？

### ISSUE THREAD

**Issue by HugeDog** [fex-team/jello#70]
spring集成jello时，配置文件要配置bean，里面有个百度自己的类，**com.baidu.fis.velocity.spring.FisBean**
```javascript
    <dependency>
        <groupId>com.baidu.fis.velocity</groupId>
        <artifactId>fis-velocity-tools</artifactId>
        <version>1.3</version>
    </dependency>
```
这个jar包找不到。

另外，我是用的gradle构建。

**Comment by 2betop** [comment]
重复问题： https://github.com/fex-team/fex-team.github.io/issues/26#issuecomment-136241424
