### ISSUE TITLE
运行jello server start 开启服务的时候，java进程被终止，该如何解决？

### ISSUE THREAD

**Issue by lotusyun** [fex-team/jello#79]
之前还能运行得好好的，今天一来跑项目跑不起来，具体现象如下：
编译代码后，
运行jello server start
提示
shutdown java process [6168]
checking java support : v1.7.0
starting fis-server.
...................... at port [8080]
 [NOTIC] browse http://127.0.0.1:8080/

然后浏览器自动打开页面，是一个404的页面，
尝试过重新安装jello 和 java都没有解决这个问题，请大侠们仗义相助

**Comment by 2betop** [comment]
jello server clean 然后重新 release 试试

**Comment by lotusyun** [comment]
解决了，原因是不小心把WEB-INF中的web.xml 文件弄丢了，解决方法，删掉www中的所有文件后release搞定。

试过用别人pc机子上的web.xml 或者 自己mac系统中的web.xml，均报错不能启动。
