### ISSUE TITLE
#parse('/widget/common/header.vm')如何资源定位？

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/jello#80]
发布给后端javaer和发布给自己tomcat测试环境的路径不一致的话，想知道怎么解决？

我现在在perprocessor里用正则替换#parse关键字，感觉其他人也应该遇到同样问题吧，怎么解决的？多谢

**Comment by 2betop** [comment]
可以考虑用 `#widget` 要用 `#parse` 的话，只能像你说的那样写个 ppreproccessor

**Comment by jiajianrong** [comment]
OK
