### ISSUE TITLE
npm install jello --save报错

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/jello#81]
> D:\npm开发\j58>npm install jello --save
npm WARN package.json j58@0.0.1 No description
npm WARN package.json j58@0.0.1 No repository field.
npm WARN package.json j58@0.0.1 No README data
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fai
l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
e.
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "jello" "--save"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! shasum check failed for C:\Users\58\AppData\Local\Temp\npm-5332-e373080
a\registry.npmjs.org\node-pngquant-native\-\node-pngquant-native-1.0.3.tgz
npm ERR! Expected: 925c943c43fc352206c177fed1559ec7144f7f12
npm ERR! Actual:   f2bfa49924cb7f9596e71a014737b38f7b49747b
npm ERR! From:     https://registry.npmjs.org/node-pngquant-native/-/node-pngqua
nt-native-1.0.3.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 fis@1.9.44 uninstall D:\npm开发\j58\node_modules\jello\node_modules\fis
 node -e "var cp = require('child_process'); cp.exec('bin/fis server stop');"
npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm开发\j58\npm-debug.log

但是
npm install jello@1.0.7 --save是正常的，新版fis里有什么问题吗？
多谢

**Comment by xiangshouding** [comment]
npm 常见问题

```
npm cache clean
```

后重试

**Comment by jiajianrong** [comment]
解决了，赞
多谢
