### ISSUE TITLE
cnpm install -g fis-parser-sass安装插件失败

### ISSUE THREAD

**Issue by milsevol** [fex-team/jello#93]
Downloading fis-parser-sass to C:\Users\xueyong\AppData\Roaming\npm\node_modules
\fis-parser-sass_tmp
Copying C:\Users\xueyong\AppData\Roaming\npm\node_modules\fis-parser-sass_tmp\_f
is-parser-sass@0.3.16@fis-parser-sass to C:\Users\xueyong\AppData\Roaming\npm\no
de_modules\fis-parser-sass
Installing fis-parser-sass's dependencies to C:\Users\xueyong\AppData\Roaming\np
m\node_modules\fis-parser-sass/node_modules
[1/1] fis-sass@^3.1.0 installed at node_modules\_fis-sass@3.1.3@fis-sass
execute post install 1 scripts...
[1/1] scripts.install fis-sass@^3.1.0 run "node build.js"
Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/win32-ia32/0.12.0/b
inding.node ...
Received 515K...
Received 832K total.
Test failed!
(node:4704) DeprecationWarning: child_process: options.customFds option is depre
cated. Use options.stdio instead.

C:\Users\xueyong\AppData\Roaming\npm\node_modules\fis-parser-sass\node_modules\_
fis-sass@3.1.3@fis-sass>node "C:\Users\xueyong\AppData\Roaming\npm\node_modules\
cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\xueyong\AppData\Roaming\npm\
node_modules\cnpm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\xueyong\AppData\Roaming\npm\n
ode_modules\cnpm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\xueyong\AppData\Roaming\npm\node_modules\cnpm\nod
e_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\word\\door\\developer\\software\\install\\nodejs\\node.exe
" "C:\\Users\\xueyong\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\
npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xueyong\AppData\Roaming\npm\node_modules\fis-parser-sass\n
ode_modules\_fis-sass@3.1.3@fis-sass
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
Install fail! Error: post install error, please remove node_modules before retry
!
Run "C:\Windows\system32\cmd.exe /d /s /c node build.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node build.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\xueyong\AppData\Roaming\npm\node_modu
les\cnpm\node_modules\runscript\index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.30.1
npminstall args: E:\word\door\developer\software\install\nodejs\node.exe C:\User
s\xueyong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\inst
all.js --china --userconfig=C:\Users\xueyong\.cnpmrc --disturl=https://npm.taoba
o.org/mirrors/node --registry=https://registry.npm.taobao.org -g fis-parser-sass
E:\word\door\developer\code\github\jello\jello-demo>cnpm install fis-parser-sass
 -g

Downloading fis-parser-sass to C:\Users\xueyong\AppData\Roaming\npm\node_modules
\fis-parser-sass_tmp
Copying C:\Users\xueyong\AppData\Roaming\npm\node_modules\fis-parser-sass_tmp\_f
is-parser-sass@0.3.16@fis-parser-sass to C:\Users\xueyong\AppData\Roaming\npm\no
de_modules\fis-parser-sass
Installing fis-parser-sass's dependencies to C:\Users\xueyong\AppData\Roaming\np
m\node_modules\fis-parser-sass/node_modules
[1/1] fis-sass@^3.1.0 installed at node_modules\_fis-sass@3.1.3@fis-sass
execute post install 1 scripts...
[1/1] scripts.install fis-sass@^3.1.0 run "node build.js"
Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/win32-ia32/0.12.0/b
inding.node ...
Received 512K...
Received 832K total.
Test failed!
(node:6380) DeprecationWarning: child_process: options.customFds option is depre
cated. Use options.stdio instead.

C:\Users\xueyong\AppData\Roaming\npm\node_modules\fis-parser-sass\node_modules\_
fis-sass@3.1.3@fis-sass>node "C:\Users\xueyong\AppData\Roaming\npm\node_modules\
cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\xueyong\AppData\Roaming\npm\
node_modules\cnpm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\xueyong\AppData\Roaming\npm\n
ode_modules\cnpm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\xueyong\AppData\Roaming\npm\node_modules\cnpm\nod
e_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\word\\door\\developer\\software\\install\\nodejs\\node.exe
" "C:\\Users\\xueyong\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\
npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xueyong\AppData\Roaming\npm\node_modules\fis-parser-sass\n
ode_modules\_fis-sass@3.1.3@fis-sass
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
Install fail! Error: post install error, please remove node_modules before retry
!
Run "C:\Windows\system32\cmd.exe /d /s /c node build.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node build.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\xueyong\AppData\Roaming\npm\node_modu
les\cnpm\node_modules\runscript\index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.30.1
npminstall args: E:\word\door\developer\software\install\nodejs\node.exe C:\User
s\xueyong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\inst
all.js --china --userconfig=C:\Users\xueyong\.cnpmrc --disturl=https://npm.taoba
o.org/mirrors/node --registry=https://registry.npm.taobao.org fis-parser-sass -g

**Comment by milsevol** [comment]
百度了一下，有人遇到相同的问题
[就在这里](http://ask.csdn.net/questions/219745)
好像是要用fis-node-parser-sass替换
好吧，我安装这个fis-node-parser-sass，还是没有解决。
给位有遇到相同问题的吗？

**Comment by oxUnd** [comment]
@milsevol NPM 的使用问题，请参考  https://github.com/fex-team/fis/issues/565
